export const FETCH_SYSTEM_SETTING_EDIT = 'FETCH_SYSTEM_SETTING_EDIT'

export const FETCH_SYSTEM_MANAGEMENT_LIST = 'FETCH_SYSTEM_MANAGEMENT_LIST'
export const ADD_SYSTEM_MANAGEMENT_LIST = 'ADD_SYSTEM_MANAGEMENT_LIST'
export const DELETE_SYSTEM_MANAGEMENT_LIST = 'DELETE_SYSTEM_MANAGEMENT_LIST'
export const UPDATE_SYSTEM_MANAGEMENT_LIST  = 'UPDATE_SYSTEM_MANAGEMENT_LIST'
export const CHECK_SYSTEM_MANAGEMENT_LIST = 'CHECK_SYSTEM_MANAGEMENT_LIST'

export const FETCH_SYSTEM_ADMIN_LIST = 'FETCH_SYSTEM_ADMIN_LIST'
export const DELETE_SYSTEM_ADMIN_ITEM = 'DELETE_SYSTEM_ADMIN_ITEM'
export const ADD_SYSTEM_ADMIN_ITEM = 'ADD_SYSTEM_ADMIN_ITEM'
export const UPDATE_SYSTEM_ADMIN_ITEM = 'UPDATE_SYSTEM_ADMIN_ITEM'

export const FETCH_ADMIN_GROUP_LIST = 'FETCH_ADMIN_GROUP_LIST'

export const FETCH_SYSTEM_HELP_LIST = 'FETCH_SYSTEM_HELP_LIST'
export const ADD_SYSTEM_HELP_NODE = 'ADD_SYSTEM_HELP_NODE'
export const DEL_SYSTEM_HELP_NODE = 'DEL_SYSTEM_HELP_NODE'
export const UPDATE_SYSTEM_HELP_NODE = 'UPDATE_SYSTEM_HELP_NODE'

export const FETCH_STATUS_CODE_LIST = 'FETCH_STATUS_CODE_LIST'
export const ADD_STATUS_CODE_LIST = 'ADD_STATUS_CODE_LIST'
export const UPDATE_STATUS_CODE_LIST = 'UPDATE_STATUS_CODE_LIST'

export const FETCH_MENU_LIST_PAGE = 'FETCH_MENU_LIST_PAGE'
export const FETCH_SYSTEM_MENU_LIST = 'FETCH_SYSTEM_MENU_LIST'
export const UPDATE_SYSTEM_MENU_LIST = 'UPDATE_SYSTEM_MENU_LIST'
export const FETCH_SYSTEM_MENU_TYPE = 'FETCH_SYSTEM_MENU_TYPE'
export const CREATE_SYSTEM_MENU = 'CREATE_SYSTEM_MENU'

export const FETCH_NET_WORK_LIST = 'FETCH_NET_WORK_LIST'
export const ADD_NET_WORK_LIST = 'ADD_NET_WORK_LIST'
export const DELETE_NET_WORK_LIST = 'DELETE_NET_WORK_LIST'
export const UPDATE_NET_WORK_LIST = 'UPDATE_NET_WORK_LIST'

export const FETCH_SYSTEM_ROLE_LIST = 'FETCH_SYSTEM_ROLE_LIST'
export const DELETE_SYSTEM_ROLE = 'DELETE_SYSTEM_ROLE'
export const FETCH_SYSTEM_ROLE_MODAL_DATA = 'FETCH_SYSTEM_ROLE_MODAL_DATA'
export const ADD_SYSTEM_ROLE = 'ADD_SYSTEM_ROLE'

export const FETCH_SYSTEM_AUTH_LIST = 'FETCH_SYSTEM_AUTH_LIST'
export const FETCH_SYSTEM_AUTH_EDIT_DATA = 'FETCH_SYSTEM_AUTH_EDIT_DATA'
export const DELETE_SYSTEM_AUTH_PACKAGE = 'DELETE_SYSTEM_AUTH_PACKAGE'
export const ADD_SYSTEM_AUTH_PACKAGE = 'ADD_SYSTEM_AUTH_PACKAGE'
export const UPDATE_SYSTEM_AUTH_PACKAGE = 'UPDATE_SYSTEM_AUTH_PACKAGE'

export const FETCH_SYSTEM_SETTING_DATA = 'FETCH_SYSTEM_SETTING_DATA'
export const UPDATE_SYSTEM_SETTING_DATA = 'UPDATE_SYSTEM_SETTING_DATA'

export const FETCH_SYSTEM_DEPARTMENT_LIST = 'FETCH_SYSTEM_DEPARTMENT_LIST'
export const FETCH_SYSTEM_DEPARTMENT_BYID = 'FETCH_SYSTEM_DEPARTMENT_BYID'
export const FETCH_SYSTEM_DEPARTMENT_SELECTOR = 'FETCH_SYSTEM_DEPARTMENT_SELECTOR'
export const FETCH_DEPARTMENT_GROUP_LIST = 'FETCH_DEPARTMENT_GROUP_LIST'
export const DELETE_SYSTEM_DEPARTMENT = 'DELETE_SYSTEM_DEPARTMENT'
export const SAVE_SYSTEM_DEPARTMENT = 'SAVE_SYSTEM_DEPARTMENT'
export const UPDATE_SYSTEM_DEPARTMENT = 'UPDATE_SYSTEM_DEPARTMENT'
export const GET_SYSTEM_ORGANIZATION_OPTION = 'GET_SYSTEM_ORGANIZATION_OPTION'

export const FETCH_SYSTEM_LOG_LIST = 'FETCH_SYSTEM_LOG_LIST'

export const FETCH_SYSTEM_KEY_LIST = 'FETCH_SYSTEM_KEY_LIST'
export const ADD_SYSTEM_KEY_LIST = 'ADD_SYSTEM_KEY_LIST'
export const DELETE_SYSTEM_KEY_LIST = 'DELETE_SYSTEM_KEY_LIST'
export const UPDATE_SYSTEM_KEY_LIST = 'UPDATE_SYSTEM_KEY_LIST'

//机构管理
export const FETCH_SYSTEM_ORGANIZATION_LIST = 'FETCH_SYSTEM_ORGANIZATION_LIST'
export const ADD_SYSTEM_ORGANIZATION_LIST = 'ADD_SYSTEM_ORGANIZATION_LIST'
export const UPDATE_SYSTEM_ORGANIZATION_LIST = 'UPDATE_SYSTEM_ORGANIZATION_LIST'
export const DELETE_SYSTEM_ORGANIZATION_LIST = 'DELETE_SYSTEM_ORGANIZATION_LIST'

//系统群组
export const FETCH_SYSTEM_GROUP_LIST = 'FETCH_SYSTEM_GROUP_LIST'
export const ADD_SYSTEM_GROUP_LIST = 'ADD_SYSTEM_GROUP_LIST'
export const UPDATE_SYSTEM_GROUP_LIST = 'UPDATE_SYSTEM_GROUP_LIST'
export const DELETE_SYSTEM_GROUP_LIST = 'DELETE_SYSTEM_GROUP_LIST'
export const CHECK_SYSTEM_GROUP_LIST = 'CHECK_SYSTEM_GROUP_LIST'
export const GET_SYSTEM_GROUP_LIST = 'GET_SYSTEM_GROUP_LIST'