//微信墙设置
export const FETCH_WALL_SETTING_LAYOUT = 'FETCH_WALL_SETTING_LAYOUT'
export const ADD_WALL_SETTING_LAYOUT = 'ADD_WALL_SETTING_LAYOUT' 
export const UPDATE_WALL_SETTING_LAYOUT = 'UPDATE_WALL_SETTING_LAYOUT' 
export const DELETE_WALL_SETTING_LAYOUT = 'DELETE_WALL_SETTING_LAYOUT' 

export const FETCH_WALL_SETTING_THEME = 'FETCH_WALL_SETTING_THEME'
export const ADD_WALL_SETTING_THEME = 'ADD_WALL_SETTING_THEME' 
export const UPDATE_WALL_SETTING_THEME = 'UPDATE_WALL_SETTING_THEME' 
export const DELETE_WALL_SETTING_THEME = 'DELETE_WALL_SETTING_THEME' 

export const FETCH_WALL_SETTING_TEMPLATE = 'FETCH_WALL_SETTING_TEMPLATE'
export const ADD_WALL_SETTING_TEMPLATE = 'ADD_WALL_SETTING_TEMPLATE'
export const UPDATE_WALL_SETTING_TEMPLATE = 'UPDATE_WALL_SETTING_TEMPLATE'
export const DELETE_WALL_SETTING_TEMPLATE = 'DELETE_WALL_SETTING_TEMPLATE'
export const GET_WALL_SETTING_EDIT_TEMPLATE = 'GET_WALL_SETTING_EDIT_TEMPLATE'
export const CHECK_WALL_SETTING_TEMPLATE = 'CHECK_WALL_SETTING_TEMPLATE'

export const FETCH_WALL_ACTIVITY_TEMPLATE = 'FETCH_WALL_ACTIVITY_TEMPLATE'
export const ADD_WALL_ACTIVITY_TEMPLATE = 'ADD_WALL_ACTIVITY_TEMPLATE'
export const UPDATE_WALL_ACTIVITY_TEMPLATE = 'UPDATE_WALL_ACTIVITY_TEMPLATE'
export const DELETE_WALL_ACTIVITY_TEMPLATE = 'DELETE_WALL_ACTIVITY_TEMPLATE'


//微信墙详情
// ＃DEL-START
export const FETCH_WALLDETAIL_STATISTICS_LIST = 'FETCH_WALLDETAIL_STATISTICS_LIST'
export const FETCH_WALLDETAIL_PRIZE_LIST = 'FETCH_WALLDETAIL_PRIZE_LIST'
export const FETCH_WALLDETAIL_VOTE_LIST = 'FETCH_WALLDETAIL_VOTE_LIST'
export const FETCH_WALLDETAIL_SHAKEPRIZE_LIST = 'FETCH_WALLDETAIL_SHAKEPRIZE_LIST'
export const FETCH_WALLDETAIL_SHAKE_LIST = 'FETCH_WALLDETAIL_SHAKE_LIST'
export const FETCH_WALLDETAIL_MONEY_LIST = 'FETCH_WALLDETAIL_MONEY_LIST'
export const FETCH_WALLDETAIL_BUMP_LIST = 'FETCH_WALLDETAIL_BUMP_LIST'
export const FETCH_WALLDETAIL_SCREENCTRL_LIST = 'FETCH_WALLDETAIL_SCREENCTRL_LIST'

export const FETCH_WALL_MESSAGE_ADUIT_LIST = 'FETCH_WALL_MESSAGE_ADUIT_LIST'
export const FETCH_WALL_RUN_LIST = 'FETCH_WALL_RUN_LIST'
export const FETCH_WALL_UNPASS_LIST = 'FETCH_WALL_UNPASS_LIST'
export const FETCH_WALL_NAME_LIST = 'FETCH_WALL_NAME_LIST'
export const UPDATE_WALL_MESSAGE_ADUIT_SETTING = 'UPDATE_WALL_MESSAGE_ADUIT_SETTING'

export const WALL_PASS_ADUIT_ITEM = 'WALL_PASS_ADUIT_ITEM'
export const WALL_UNPASS_ADUIT_ITEM = 'WALL_UNPASS_ADUIT_ITEM'
export const FETCH_LIVE_MESSAGE_LIST = 'FETCH_LIVE_MESSAGE_LIST'
export const DELETE_LIVE_MESSAGE_LIST = 'DELETE_LIVE_MESSAGE_LIST'
export const FETCH_WALL_SCREEN_CTRL = 'FETCH_WALL_SCREEN_CTRL'
export const UPDATE_WALL_SCREEN_CTRL = 'UPDATE_WALL_SCREEN_CTRL'

export const UPDATE_WALL_SCREEN_PNUM = 'UPDATE_WALL_SCREEN_PNUM'

export const FETCH_VIRTUAL_ROLE_LIST = 'FETCH_VIRTUAL_ROLE_LIST'
export const ADD_VIRTUAL_ROLE_LIST = 'ADD_VIRTUAL_ROLE_LIST'
export const UPDATE_VIRTUAL_ROLE_LIST = 'UPDATE_VIRTUAL_ROLE_LIST'
export const DELETE_VIRTUAL_ROLE_LIST = 'DELETE_VIRTUAL_ROLE_LIST'
export const FETCH_VIRTUAL_MESSAGE_LIST = 'FETCH_VIRTUAL_MESSAGE_LIST'

export const FETCH_WALL_WORD_LIST = 'FETCH_WALL_WORD_LIST'
export const ADD_WALL_WORD_LIST = 'ADD_WALL_WORD_LIST'
export const DELETE_WALL_WORD_LIST = 'DELETE_WALL_WORD_LIST'
export const DELETE_WALL_WORDS_LIST = 'DELETE_WALL_WORDS_LIST'


// ＃DEL-END
// 微信墙首页列表
export const FETCH_WALL_ACTIVITY_ALL = 'FETCH_WALL_ACTIVITY_ALL'
export const SAVE_WALL_ACTIVITY = 'SAVE_WALL_ACTIVITY'
export const DELETE_WALL_ACTIVITY = 'DELETE_WALL_ACTIVITY'
export const UPDATE_WALL_ACTIVITY = 'UPDATE_WALL_ACTIVITY'

// 微信墙－活动功能／START
export const FETCH_ACTIVITY_BYID = 'FETCH_ACTIVITY_BYID'
export const FETCH_WALL_MSGREVIEW = 'FETCH_WALL_MSGREVIEW'
export const UPDATE_WALL_MSGREVIEW = 'UPDATE_WALL_MSGREVIEW'
export const FETCH_WALL_GUEST_LIST = 'FETCH_WALL_GUEST_LIST'
export const ADD_WALL_GUEST = 'ADD_WALL_GUEST'
export const UPDATE_WALL_GUEST = 'UPDATE_WALL_GUEST'
export const DELETE_WALL_GUEST = 'DELETE_WALL_GUEST'
export const ADD_WALL_PHOTO = 'ADD_WALL_PHOTO'
export const DELETE_WALL_PHOTO = 'DELETE_WALL_PHOTO'
export const FETCH_PHOTO_LIST = 'FETCH_PHOTO_LIST'
export const ADD_WALL_PRIZE = 'ADD_WALL_PRIZE'
export const DELETE_WALL_PRIZE = 'DELETE_WALL_PRIZE'
export const UPDATE_WALL_PRIZE = 'UPDATE_WALL_PRIZE'
export const FETCH_WALL_PRIZE = 'FETCH_WALL_PRIZE'
export const FETCH_WALL_PRIZE_SELECT = 'FETCH_WALL_PRIZE_SELECT'
export const FETCH_WALL_SHAKE_LIST = 'FETCH_WALL_SHAKE_LIST'
export const UPDATE_WALL_SHAKE_CONFIG = 'UPDATE_WALL_SHAKE_CONFIG'
export const DELETE_WALL_SHAKE = 'DELETE_WALL_SHAKE'
export const ADD_WALL_SHAKE = 'ADD_WALL_SHAKE'
export const UPDATE_WALL_SHAKE = 'UPDATE_WALL_SHAKE'
export const FETCH_WALL_MSTCHING_INFO = 'FETCH_WALL_MSTCHING_INFO'
export const UPDATE_WALL_MSTCHING_INFO = 'UPDATE_WALL_MSTCHING_INFO'
export const UPDATE_WALL_MSTCHING_STATUS = 'UPDATE_WALL_MSTCHING_STATUS'
export const FETCH_WALL_MONEY_INFO = 'FETCH_WALL_MONEY_INFO'
export const ADD_MONEY_INFO = 'ADD_MONEY_INFO'
export const UPDATE_MONEY_INFO = 'UPDATE_MONEY_INFO'
export const DELETE_MONEY_INFO = 'DELETE_MONEY_INFO'
export const FETCH_WALL_VOTE_LIST = 'FETCH_WALL_VOTE_LIST'
export const SAVE_WALL_VOTE = 'SAVE_WALL_VOTE'
export const UPDATE_WALL_VOTE = 'UPDATE_WALL_VOTE'
export const DELETE_WALL_VOTE = 'DELETE_WALL_VOTE'
export const UPDATE_SHAKE_PRIZE_CONFIG = 'UPDATE_SHAKE_PRIZE_CONFIG'
export const FETCH_SHAKE_RPIZE_LIST = 'FETCH_SHAKE_RPIZE_LIST'
export const SAVE_WALL_SHAKE_PRIZE = 'SAVE_WALL_SHAKE_PRIZE'
export const UPDATE_WALL_SHAKE_PRIZE = 'UPDATE_WALL_SHAKE_PRIZE'
export const DELETE_WALL_SHAKE_PRIZE = 'DELETE_WALL_SHAKE_PRIZE'
// 微信墙－活动功能／END

// 微信墙－签到／START
export const UPDATE_WALL_SIGN_SETTING = 'UPDATE_WALL_SIGN_SETTING'
export const FETCH_WALL_SIGN_SETTING = 'FETCH_WALL_SIGN_SETTING'
export const FETCH_WALL_WHITE_LIST = 'FETCH_WALL_WHITE_LIST'
export const ADD_WALL_WHITE_NAME = 'ADD_WALL_WHITE_NAME'
export const DELETE_WALL_WHITE_NAME = 'DELETE_WALL_WHITE_NAME'
export const UPDATE_WALL_WHITE_NAME = 'UPDATE_WALL_WHITE_NAME'
// 微信墙－签到／END

// 微信墙-活动数据统计/START
export const FETCH_ACTIVITY_DATA_BYID = 'FETCH_ACTIVITY_DATA_BYID'
export const SET_USER_DRAW_STATUS = 'SET_USER_DRAW_STATUS'
export const FETCH_DRAW_DATA_BYID = 'FETCH_DRAW_DATA_BYID'
export const FETCH_ACTIVITY_BUMP_LIST = 'FETCH_ACTIVITY_BUMP_LIST'
export const FETCH_ACTIVITY_SHAKEPRIZE_LIST = 'FETCH_ACTIVITY_SHAKEPRIZE_LIST'
export const FETCH_ACTIVITY_SHAKE_LIST = 'FETCH_ACTIVITY_SHAKE_LIST'
export const FETCH_ACTIVITY_MONEY_LIST = 'FETCH_ACTIVITY_MONEY_LIST'
export const FETCH_ACTIVITY_VOTE_LIST = ' FETCH_ACTIVITY_VOTE_LIST '
export const FETCH_ACTIVITY_VOTE_PEOPLE = 'FETCH_ACTIVITY_VOTE_PEOPLE'
// 微信墙-活动数据统计/END

//照片墙管理
export const FETCH_WALL_PHOTOMANAGEMENT_LIST = 'FETCH_WALL_PHOTOMANAGEMENT_LIST'
export const ADD_WALL_PHOTOMANAGEMENT_LIST = 'ADD_WALL_PHOTOMANAGEMENT_LIST'
export const UPDATE_WALL_PHOTOMANAGEMENT_LIST = 'UPDATE_WALL_PHOTOMANAGEMENT_LIST'
export const DELETE_WALL_PHOTOMANAGEMENT_LIST = 'DELETE_WALL_PHOTOMANAGEMENT_LIST'
export const FETCH_WALL_PHOTOMANAGEMENT_EDIT_SELECT = 'FETCH_WALL_PHOTOMANAGEMENT_EDIT_SELECT'
export const FETCH_WALL_PHOTOMANAGEMENT_DETAIL = 'FETCH_WALL_PHOTOMANAGEMENT_DETAIL'

//照片墙审核
export const FETCH_WALL_AUDIT_LIST = 'FETCH_WALL_AUDIT_LIST'
export const PASS_WALL_AUDIT_LIST = 'PASS_WALL_AUDIT_LIST'
export const FAIL_WALL_AUDIT_LIST = 'FAIL_WALL_AUDIT_LIST'
export const PASS_WALL_BATCHAUDIT_LIST = 'PASS_WALL_BATCHAUDIT_LIST'
export const FAIL_WALL_BATCHAUDIT_LIST = 'FAIL_WALL_BATCHAUDIT_LIST'

//照片墙记录
export const FETCH_WALL_RECORD_LIST = 'FETCH_WALL_RECORD_LIST'
export const DELETE_WALL_RECORD_LIST = 'DELETE_WALL_RECORD_LIST'
