//图片库
export const FETCH_CARD_VOUCHER_PHOTOS = 'FETCH_CARD_VOUCHER_PHOTOS'
export const CHECK_CARD_VOUCHER_PHOTOS = 'CHECK_CARD_VOUCHER_PHOTOS'
export const ADD_CARD_VOUCHER_PHOTOS = 'ADD_CARD_VOUCHER_PHOTOS'
export const DEL_CARD_VOUCHER_PHOTOS = 'DEL_CARD_VOUCHER_PHOTOS'
export const UPDATE_CARD_VOUCHER_PHOTOS = 'UPDATE_CARD_VOUCHER_PHOTOS'

//门店系统
export const FETCH_STORE_LISTS = 'FETCH_STORE_LISTS'
export const GET_STATUS_SELECT_LIST = 'GET_STATUS_SELECT_LIST'
export const ADD_STORE = 'ADD_STORE'
export const GET_STORES_EDIT_SELECT = 'GET_STORES_EDIT_SELECT'
export const GET_TOP_DISTRICTS = 'GET_TOP_DISTRICTS'
export const GET_TOP_DISTRICTS_CHILD = 'GET_TOP_DISTRICTS_CHILD'
export const SEARCH_MAP_BY_KEYWORD = 'SEARCH_MAP_BY_KEYWORD'
export const GET_DETAIL_LOCATION = 'GET_DETAIL_LOCATION'
export const CHECK_STORE = 'CHECK_STORE'
export const EDIT_STORE = 'EDIT_STORE'
export const SYNC_STORE_LIST = 'SYNC_STORE_LIST'
export const SYNC_STORE_ONE = 'SYNC_STORE_ONE'
export const DELETE_STORE = 'DELETE_STORE'

//路由
export const FETCH_CARD_VOUCHER_ROUTES = 'FETCH_CARD_VOUCHER_ROUTES'
export const CHECK_CARD_VOUCHER_ROUTE = 'CHECK_CARD_VOUCHER_ROUTE'
export const ADD_CARD_VOUCHER_ROUTE = 'ADD_CARD_VOUCHER_ROUTE'
export const DEL_CARD_VOUCHER_ROUTE = 'DEL_CARD_VOUCHER_ROUTE'
export const UPDATE_CARD_VOUCHER_ROUTE = 'UPDATE_CARD_VOUCHER_ROUTE'
export const FETCH_CARD_VOUCHER_CARD_LIST = 'FETCH_CARD_VOUCHER_CARD_LIST'

//白名单
export const FETCH_CARD_VOUCHER_WHITE = 'FETCH_CARD_VOUCHER_WHITE'
export const CHECK_CARD_VOUCHER_WHITE = 'CHECK_CARD_VOUCHER_WHITE'
export const ADD_CARD_VOUCHER_WHITE = 'ADD_CARD_VOUCHER_WHITE'
export const DEL_CARD_VOUCHER_WHITE = 'DEL_CARD_VOUCHER_WHITE'
export const UPDATE_CARD_VOUCHER_WHITE = 'UPDATE_CARD_VOUCHER_WHITE'
export const GET_STATUS_SELECT_WHITE = 'GET_STATUS_SELECT_WHITE'
export const GET_STATUS_SELECT_PULL = 'GET_STATUS_SELECT_PULL'

//二维码
export const FETCH_CARD_VOUCHER_QRCODES = 'FETCH_CARD_VOUCHER_QRCODES'
export const CHECK_CARD_VOUCHER_QRCODE = 'CHECK_CARD_VOUCHER_QRCODE'
export const ADD_CARD_VOUCHER_QRCODE = 'ADD_CARD_VOUCHER_QRCODE'
export const DEL_CARD_VOUCHER_QRCODE = 'DEL_CARD_VOUCHER_QRCODE'
export const UPDATE_CARD_VOUCHER_QRCODE = 'UPDATE_CARD_VOUCHER_QRCODE'
export const FETCH_CARD_VOUCHER_QRCODE_SELECTOR = 'FETCH_CARD_VOUCHER_QRCODE_SELECTOR'
export const GENERATE_CARD_VOUCHER_QRCODE = 'GENERATE_CARD_VOUCHER_QRCODE'

//卡卷对换
export const FETCH_CARD_VOUCHER_REDEEM = 'FETCH_CARD_VOUCHER_REDEEM'
export const CHECK_CARD_VOUCHER_REDEEM = 'CHECK_CARD_VOUCHER_REDEEM'
export const ADD_CARD_VOUCHER_REDEEM = 'ADD_CARD_VOUCHER_REDEEM'
export const DEL_CARD_VOUCHER_REDEEM = 'DEL_CARD_VOUCHER_REDEEM'
export const UPDATE_CARD_VOUCHER_REDEEM = 'UPDATE_CARD_VOUCHER_REDEEM'
export const GET_STATUS_SELECT_REDEEM = 'GET_STATUS_SELECT_REDEEM'
export const GET_STATUS_SELECT_PULLR = 'GET_STATUS_SELECT_PULLR'

//卡券记录
export const FETCH_CARD_VOUCHER_RECORD = 'FETCH_CARD_VOUCHER_RECORD'
export const CHECK_CARD_VOUCHER_RECORD = 'CHECK_CARD_VOUCHER_RECORD'
export const FETCH_CARD_VOUCHER_RECORD_SELECTOR = 'FETCH_CARD_VOUCHER_RECORD_SELECTOR'

//卡券记录
export const FETCH_CARD_VOUCHER_GIFTING_RECORD = 'FETCH_CARD_VOUCHER_GIFTING_RECORD'
export const CHECK_CARD_VOUCHER_GIFTING_RECORD = 'CHECK_CARD_VOUCHER_GIFTING_RECORD'

//卡券货架
export const FETCH_CARD_VOUCHER_SHELVES = 'FETCH_CARD_VOUCHER_SHELVES'
export const ADD_CARD_VOUCHER_SHELVES = 'ADD_CARD_VOUCHER_SHELVES'
export const UPDATE_CARD_VOUCHER_SHELVES = 'UPDATE_CARD_VOUCHER_SHELVES'
export const DEL_CARD_VOUCHER_SHELVES = 'DEL_CARD_VOUCHER_SHELVES'
export const CHECK_CARD_VOUCHER_SHELVES = 'CHECK_CARD_VOUCHER_SHELVES'
export const FETCH_CARD_VOUCHER_SHELVES_LIST_SELECTOR = 'FETCH_CARD_VOUCHER_SHELVES_LIST_SELECTOR'
export const FETCH_CARD_VOUCHER_SHELVES_EDIT_SELECTOR = 'FETCH_CARD_VOUCHER_SHELVES_EDIT_SELECTOR'
export const SYNCH_CARD_VOUCHER_SHELVES = 'SYNCH_CARD_VOUCHER_SHELVES'
