//积分
export const FETCH_INTEGRAL_USER_LIST = 'FETCH_INTEGRAL_USER_LIST'
export const FETCH_INTEGRAL_LOG_LIST = 'FETCH_INTEGRAL_LOG_LIST'
export const FETCH_SINGER_USER_RECORD = 'FETCH_SINGER_USER_RECORD'