
//宜停车
export const FETCH_PARK_TICKET_LIST = 'FETCH_PARK_TICKET_LIST'
export const FETCH_PARK_REQUEST_LIST = 'FETCH_PARK_REQUEST_LIST'
export const FETCH_PARK_MESSAGE_LIST = 'FETCH_PARK_MESSAGE_LIST'
export const FETCH_PARK_ORDER_LIST = 'FETCH_PARK_ORDER_LIST'