//活动
//活动管理
export const FETCH_ACTIVITY_MANAGEMENT_LIST = 'FETCH_ACTIVITY_MANAGEMENT_LIST'
export const FETCH_ACTIVITY_EDIT_SELECT = 'FETCH_ACTIVITY_EDIT_SELECT'
export const FETCH_ACTIVITY_MANAGEMENT_DETAIL = 'FETCH_ACTIVITY_MANAGEMENT_DETAIL'
export const ADD_ACTIVITY_MANAGEMENT_LIST = 'ADD_ACTIVITY_MANAGEMENT_LIST'
export const UPDATE_ACTIVITY_MANAGEMENT_LIST = 'UPDATE_ACTIVITY_MANAGEMENT_LIST'
export const DELETE_ACTIVITY_MANAGEMENT_LIST = 'DELETE_ACTIVITY_MANAGEMENT_LIST'
export const FETCH_ACTIVITY_SETTING_LIST = 'FETCH_ACTIVITY_SETTING_LIST'
export const FETCH_ACTIVITY_SETTING_DETAIL = 'FETCH_ACTIVITY_SETTING_DETAIL'
export const ADD_ACTIVITY_SETTING_LIST = 'ADD_ACTIVITY_SETTING_LIST'
export const UPDATE_ACTIVITY_SETTING_LIST = 'UPDATE_ACTIVITY_SETTING_LIST'
export const DELETE_ACTIVITY_SETTING_LIST = 'DELETE_ACTIVITY_SETTING_LIST'

//活动规则库
export const FETCH_ACTIVITY_RULE_LIST = 'FETCH_ACTIVITY_RULE_LIST'
export const ADD_ACTIVITY_RULE_LIST = 'ADD_ACTIVITY_RULE_LIST'
export const UPDATE_ACTIVITY_RULE_LIST = 'UPDATE_ACTIVITY_RULE_LIST'
export const DELETE_ACTIVITY_RULE_LIST = 'DELETE_ACTIVITY_RULE_LIST'
export const FETCH_RULE_EDIT_SELECT = 'FETCH_RULE_EDIT_SELECT'

//赞助方管理
export const FETCH_ACTIVITY_SUPPORT_LIST = 'FETCH_ACTIVITY_SUPPORT_LIST'
export const ADD_ACTIVITY_SUPPORT_LIST = 'ADD_ACTIVITY_SUPPORT_LIST'
export const UPDATE_ACTIVITY_SUPPORT_LIST = 'UPDATE_ACTIVITY_SUPPORT_LIST'
export const DELETE_ACTIVITY_SUPPORT_LIST = 'DELETE_ACTIVITY_SUPPORT_LIST'

//活动奖品
export const FETCH_ACTIVITY_PRIZE_LIST = 'FETCH_ACTIVITY_PRIZE_LIST'
export const ADD_ACTIVITY_PRIZE_LIST = 'ADD_ACTIVITY_PRIZE_LIST'
export const UPDATE_ACTIVITY_PRIZE_LIST = 'UPDATE_ACTIVITY_PRIZE_LIST'
export const DELETE_ACTIVITY_PRIZE_LIST = 'DELETE_ACTIVITY_PRIZE_LIST'
export const FETCH_PRIZE_EDIT_SELECT = 'FETCH_PRIZE_EDIT_SELECT'
export const FETCH_ACTIVITY_PRIZE_SELECT = 'FETCH_ACTIVITY_PRIZE_SELECT'
export const FETCH_ACTIVITY_PRIZE_DETAIL = 'FETCH_ACTIVITY_PRIZE_DETAIL'

//奖品规则管理
export const FETCH_ACTIVITY_PRIZERULE_LIST = 'FETCH_ACTIVITY_PRIZERULE_LIST'
export const ADD_ACTIVITY_PRIZERULE_LIST = 'ADD_ACTIVITY_PRIZERULE_LIST'
export const UPDATE_ACTIVITY_PRIZERULE_LIST = 'UPDATE_ACTIVITY_PRIZERULE_LIST'
export const DELETE_ACTIVITY_PRIZERULE_LIST = 'DELETE_ACTIVITY_PRIZERULE_LIST'
export const FETCH_PRIZERULE_EDIT_SELECT = 'FETCH_PRIZERULE_EDIT_SELECT'

//活动兑换码
export const FETCH_ACTIVITY_CODE_LIST = 'FETCH_ACTIVITY_CODE_LIST'
export const ADD_ACTIVITY_CODE_LIST = 'ADD_ACTIVITY_CODE_LIST'
export const UPDATE_ACTIVITY_CODE_LIST = 'UPDATE_ACTIVITY_CODE_LIST'
export const DELETE_ACTIVITY_CODE_LIST = 'DELETE_ACTIVITY_CODE_LIST'
export const FETCH_CODE_EDIT_SELECT = 'FETCH_CODE_EDIT_SELECT'

//活动模板
export const FETCH_ACTIVITY_TEMPLATE_LIST = 'FETCH_ACTIVITY_TEMPLATE_LIST'
export const ADD_ACTIVITY_TEMPLATE_LIST = 'ADD_ACTIVITY_TEMPLATE_LIST'
export const UPDATE_ACTIVITY_TEMPLATE_LIST = 'UPDATE_ACTIVITY_TEMPLATE_LIST'
export const DELETE_ACTIVITY_TEMPLATE_LIST = 'DELETE_ACTIVITY_TEMPLATE_LIST'

//活动路由
export const FETCH_ACTIVITY_ROUTE_LIST = 'FETCH_ACTIVITY_ROUTE_LIST'
export const ADD_ACTIVITY_ROUTE_LIST = 'ADD_ACTIVITY_ROUTE_LIST'
export const UPDATE_ACTIVITY_ROUTE_LIST = 'UPDATE_ACTIVITY_ROUTE_LIST'
export const DELETE_ACTIVITY_ROUTE_LIST = 'DELETE_ACTIVITY_ROUTE_LIST'
export const CHECK_ACTIVITY_ROUTE_LIST = 'CHECK_ACTIVITY_ROUTE_LIST'
export const FETCH_ROUTE_EDIT_SELECT = 'FETCH_ROUTE_EDIT_SELECT'
//黑名单
export const FETCH_ACTIVITY_BLACK_LIST = 'FETCH_ACTIVITY_BLACK_LIST'
export const ADD_ACTIVITY_BLACK_LIST = 'ADD_ACTIVITY_BLACK_LIST'
export const UPDATE_ACTIVITY_BLACK_LIST = 'UPDATE_ACTIVITY_BLACK_LIST'
export const DELETE_ACTIVITY_BLACK_LIST = 'DELETE_ACTIVITY_BLACK_LIST'

//白名单
export const FETCH_ACTIVITY_WHITE_LIST = 'FETCH_ACTIVITY_WHITE_LIST'
export const ADD_ACTIVITY_WHITE_LIST = 'ADD_ACTIVITY_WHITE_LIST'
export const UPDATE_ACTIVITY_WHITE_LIST = 'UPDATE_ACTIVITY_WHITE_LIST'
export const DELETE_ACTIVITY_WHITE_LIST = 'DELETE_ACTIVITY_WHITE_LIST'

//中奖名单
export const FETCH_ACTIVITY_USERPRIZE_LIST = 'FETCH_ACTIVITY_USERPRIZE_LIST'

//分享日志
export const FETCH_ACTIVITY_SHARELOG_LIST = 'FETCH_ACTIVITY_SHARELOG_LIST'

//统计信息
export const FETCH_ACTIVITY_STATSLOG_LIST = 'FETCH_ACTIVITY_STATSLOG_LIST'
export const FETCH_ACTIVITY_STATSNUM_LIST = 'FETCH_ACTIVITY_STATSNUM_LIST'