//贺卡
//贺卡主设置
export const FETCH_CARD_SETTING_LIST = 'FETCH_CARD_SETTING_LIST'
export const ADD_CARD_SETTING_LIST = 'ADD_CARD_SETTING_LIST'
export const UPDATE_CARD_SETTING_LIST = 'UPDATE_CARD_SETTING_LIST'
export const DELETE_CARD_SETTING_LIST = 'DELETE_CARD_SETTING_LIST'
export const FETCH_CARD_SETTING_EDIT_SELECT = 'FETCH_CARD_SETTING_EDIT_SELECT'
export const FETCH_CARD_SETTING_DETAIL = 'FETCH_CARD_SETTING_DETAIL'

//贺卡类型
export const FETCH_CARD_TYPE_LIST = 'FETCH_CARD_TYPE_LIST'
export const ADD_CARD_TYPE_LIST = 'ADD_CARD_TYPE_LIST'
export const DELETE_CARD_TYPE_LIST = 'DELETE_CARD_TYPE_LIST'
export const UPDATE_CARD_TYPE_LIST = 'UPDATE_CARD_TYPE_LIST'
export const UPDATE_CARD_TYPE_STICKY = 'UPDATE_CARD_TYPE_STICKY'
export const FETCH_CARD_TYPE_AUTH = 'FETCH_CARD_TYPE_AUTH'
export const UPDATE_CARD_TYPE_AUTH = 'UPDATE_CARD_TYPE_AUTH'

//贺卡实例
export const FETCH_CARD_EXAMPLE_LIST = 'FETCH_CARD_EXAMPLE_LIST'
export const ADD_CARD_EXAMPLE_LIST = 'ADD_CARD_EXAMPLE_LIST'
export const DELETE_CARD_EXAMPLE_LIST = 'DELETE_CARD_EXAMPLE_LIST'
export const UPDATE_CARD_EXAMPLE_LIST = 'UPDATE_CARD_EXAMPLE_LIST'
export const FETCH_CARD_EXAMPLE_DETAIL = 'FETCH_CARD_EXAMPLE_DETAIL'
export const UPDATE_CARD_EXAMPLE_STICKY = 'UPDATE_CARD_EXAMPLE_STICKY'
export const FETCH_CARD_EXAMPLE_AUTH = 'FETCH_CARD_EXAMPLE_AUTH'
export const UPDATE_CARD_EXAMPLE_AUTH = 'UPDATE_CARD_EXAMPLE_AUTH'
export const FETCH_CARD_EXAMPLE_EDIT_SELECT = 'FETCH_CARD_EXAMPLE_EDIT_SELECT'

//贺卡祝福语
export const FETCH_CARD_BLESS_LIST = 'FETCH_CARD_BLESS_LIST'
export const ADD_CARD_BLESS_LIST = 'ADD_CARD_BLESS_LIST'
export const DELETE_CARD_BLESS_LIST = 'DELETE_CARD_BLESS_LIST'
export const UPDATE_CARD_BLESS_LIST = 'UPDATE_CARD_BLESS_LIST'
export const FETCH_CARD_BLESS_AUTH  = 'FETCH_CARD_BLESS_AUTH'
export const UPDATE_CARD_BLESS_AUTH  = 'UPDATE_CARD_BLESS_AUTH'

//贺卡模板
export const FETCH_CARD_TEMPLATE_LIST = 'FETCH_CARD_TEMPLATE_LIST'
export const ADD_CARD_TEMPLATE_LIST = 'ADD_CARD_TEMPLATE_LIST'
export const DELETE_CARD_TEMPLATE_LIST = 'DELETE_CARD_TEMPLATE_LIST'
export const UPDATE_CARD_TEMPLATE_LIST = 'UPDATE_CARD_TEMPLATE_LIST'

//分享列表
export const FETCH_CARD_SHARE_LIST = 'FETCH_CARD_SHARE_LIST'

//贺卡列表
export const FETCH_CARD_LIST  = 'FETCH_CARD_LIST'
export const DELETE_CARD_LIST  = 'DELETE_CARD_LIST'
export const ADD_CARD_LIST  = 'ADD_CARD_LIST'
export const UPDATE_CARD_LIST  = 'UPDATE_CARD_LIST'